---
- name: Install git-Lab
  hosts: all
  become: yes

  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add Docker’s official GPG key
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"

  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      pkg:
      - docker
      - docker.io
      - docker-containerd

  - name: Adding user to the docker group 
    shell: "usermod -aG docker \"$USER\""

#  - name: Reboot a machine after updates to apply
#    reboot:

  - name: Pull and run container witn gitLab
    shell: "sudo docker run --detach --hostname 34.68.25.31 --publish 443:443 --publish 80:80 --publish 257:257 --name gitlab --restart always --volume $GITLAB_HOME/config:/etc/gitlab --volume $GITLAB_HOME/logs:/var/log/gitlab --volume $GITLAB_HOME/data:/var/opt/gitlab gitlab/gitlab-ce:latest" 

  - name: Run git-Lab
    shell: "sudo docker logs -f gitlab"
